openapi: 3.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        count:
          type: number
        description:
          type: string
        id:
          type: string
        price:
          type: number
        title:
          type: string
      required:
        - count
        - description
        - price
        - title
        - id
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    ProductNotFound:
      type: string
info:
  title: product-service API
  description: This is the best API ever
  version: '1'
paths:
  /products:
    get:
      operationId: getProductsList
      summary: Get products
      description: Gets all products
      tags:
        - products
      parameters: []
      responses:
        '200':
          description: Status 200 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
  '/products/{productId}':
    get:
      operationId: getProductById
      summary: Get product by ID
      description: Gets product data by ID
      tags:
        - products
      parameters:
        - name: productId
          in: path
          description: ID of the product you want to get
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status 200 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Status 404 Response
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProductNotFound'
servers:
  - url: 'https://bmyfe1s3e1.execute-api.us-east-1.amazonaws.com/dev'
