---
swagger: "2.0"
info:
  description: "This is the best API ever"
  version: "2021-03-29T21:38:25Z"
  title: "product-service-dev"
host: "bmyfe1s3e1.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Get products"
      description: "Gets all products"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/ProductList"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Get product by ID"
      description: "Gets product data by ID"
      produces:
      - "text/plain"
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of the product you want to get"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "404 response"
          schema:
            $ref: "#/definitions/ProductNotFound"
definitions:
  ProductList:
    type: "array"
    items:
      $ref: "#/definitions/Product"
  ProductNotFound:
    type: "string"
  Product:
    type: "object"
    required:
    - "count"
    - "description"
    - "id"
    - "price"
    - "title"
    properties:
      price:
        type: "number"
      count:
        type: "number"
      description:
        type: "string"
      id:
        type: "string"
      title:
        type: "string"
    description: "This is an product"
